UK_UNIVERSITIES = [
    "Abertay University",
    "Aberystwyth University",
    "Anglia Ruskin University",
    "Arts University Bournemouth",
    "Aston University",
    "Bangor University",
    "Bath Spa University",
    "Birmingham City University",
    "Bournemouth University",
    "Brunel University London",
    "Cardiff Metropolitan University",
    "Cardiff University",
    "Coventry University",
    "Cranfield University",
    "De Montfort University",
    "Durham University",
    "Edge Hill University",
    "Edinburgh Napier University",
    "Falmouth University",
    "Glasgow Caledonian University",
    "Harper Adams University",
    "Imperial College London",
    "Keele University",
    "King's College London",
    "Kingston University",
    "Lancaster University",
    "Leeds Beckett University",
    "Leeds Trinity University",
    "Liverpool Hope University",
    "Liverpool John Moores University",
    "London Metropolitan University",
    "London South Bank University",
    "Loughborough University",
    "Manchester Metropolitan University",
    "Middlesex University",
    "Newcastle University",
    "Northumbria University",
    "Nottingham Trent University",
    "Oxford Brookes University",
    "Queen Margaret University",
    "Queen Mary University of London",
    "Queen's University Belfast",
    "Robert Gordon University",
    "Royal Holloway, University of London",
    "Sheffield Hallam University",
    "Solent University",
    "Staffordshire University",
    "Swansea University",
    "Teesside University",
    "The Open University",
    "Ulster University",
    "University College London",
    "University of Aberdeen",
    "University of Bath",
    "University of Birmingham",
    "University of Bradford",
    "University of Bristol",
    "University of Cambridge",
    "University of Central Lancashire",
    "University of Chester",
    "University of Dundee",
    "University of East Anglia",
    "University of East London",
    "University of Edinburgh",
    "University of Essex",
    "University of Exeter",
    "University of Glasgow",
    "University of Gloucestershire",
    "University of Greenwich",
    "University of Hertfordshire",
    "University of Huddersfield",
    "University of Hull",
    "University of Kent",
    "University of Leeds",
    "University of Leicester",
    "University of Lincoln",
    "University of Liverpool",
    "University of Manchester",
    "University of Northampton",
    "University of Nottingham",
    "University of Oxford",
    "University of Plymouth",
    "University of Portsmouth",
    "University of Reading",
    "University of Roehampton",
    "University of Salford",
    "University of Sheffield",
    "University of Southampton",
    "University of South Wales",
    "University of St Andrews",
    "University of Stirling",
    "University of Strathclyde",
    "University of Suffolk",
    "University of Sunderland",
    "University of Surrey",
    "University of Sussex",
    "University of the Arts London",
    "University of the West of England",
    "University of the West of Scotland",
    "University of Wales Trinity Saint David",
    "University of Warwick",
    "University of West London",
    "University of Westminster",
    "University of Winchester",
    "University of Wolverhampton",
    "University of Worcester",
    "University of York",
    "York St John University",
]